# Generated by Django 4.1.4 on 2022-12-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-unit_price']},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='custumor',
            new_name='customer',
        ),
    ]
