# Generated by Django 4.1.4 on 2022-12-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_custumor_to_customer_in_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='shop',
        ),
    ]
